# **DESAFIO IFOOD**

Cientista de Dados Responsável: João Pedro Martins

---
## **0. Introdução**

**Nosso desafio: Desafio Ifood**

O conjunto de dados é composto por clientes da empresa Ifood com dados sobre:

- Perfis de clientes
- Preferências do produto
- Sucessos/fracassos da campanha
- Desempenho do canal

O objetivo de hoje é fazer uma análise exploratória desses dados. Responda usando a sua ferramenta de preferência:

- Quantos dados temos? Linhas e colunas 
- Quais são as colunas numéricas?
- Temos duplicados na nossa base? Se tivermos, retire-os 
- Temos dados nulos nessa base? Será que eles indicam algo? O que fazer com eles? 
- Qual é a média, mediana, 25 percentil, 75 percentil, mínimo e máximo de cada uma das colunas numéricas? 

Vamos agora entender o perfil de clientes que temos

- Qual é o maior salário encontrado na nossa base? Veja na coluna `Income`
- Qual é a distribuição de salário na nossa base? Temos clientes que ganham muito bem e outros que não ganham muito bem? Veja na coluna `Income`
- Nossos clientes tem níveis de educação maiores ou menores? Veja na coluna `education_level`
- Quantos clientes temos em cada estado civil? Veja na coluna `marital_status`

Agora vamos ver como os dados se correlacionam

- Qual é a relação de estado civil com número de filhos? Será que as pessoas casadas têm um maior número de filhos? Filhos está na coluna `kids`
- As pessoas gastam mais ou menos em nossa plataforma quando têm filhos? Veja nas colunas `expenses` e `kids`
- Pessoas que têm um maior salário gastam mais? Veja nas colunas `Income` e `expenses` 

Vá além! 

- O que você faria com as informações que tirou das perguntas acima?
- Trace um problema de negócios e faça quantas perguntas forem necessárias para respondê-la. ​

**Importação de Bibliotecas**

In [49]:
# Importando as bíbliotecas que serão úteis para a presente análise
import pandas as pd                 # Manipulaçãp de tabelas
import seaborn as sns               # Manipulação de gráficos
import numpy as np                  # Operações matemáticas
import matplotlib.pyplot as plt     # Manipulação de gráficos

# --------------------------------------------------------------------
# Configurações adicionais:

pd.set_option("display.float_format", "{:,.2f}".format) # Faz o Pandas mostrar valores com apenas duas casas decimais e separar o milhares com ",".
pd.set_option("display.max_columns", None)              # Exibe todas as colunas sem truncar com "...".

**Carregamento dos Dados**

In [50]:
df = pd.read_csv('../../../data/datasets_profa_renata_biaggi/desafio_ifood/mkt_data.csv')

**Estrutura do projeto**
```
EDA
├── 1. Entendimento Inicial dos Dados
├── 2. Qualidade dos Dados
├── 3. Tendência Central
├── 4. Dispersão
├── 5. Distribuição e Forma
├── 6. Outliers
├── 7. Univariada (categóricas)
├── 8. Bivariada (num×num, num×cat, cat×cat)
├── 9. Multivariada (PCA, clusters, correlação)
├── 10. Temporal (se aplicável)
├── 11. Texto (se aplicável)
└── 12. Síntese e hipóteses
```

---
## **1. Entendimento Inicial dos Dados**

Antes de qualquer cálculo, você precisa saber o que tem nas mãos.

- **Shape** — quantas linhas e colunas existem
- **Tipos de variáveis** — numéricas, categóricas, datas, booleanas
- **Primeiras e últimas linhas** — `head()` e `tail()` para checar se os dados fazem sentido visualmente
- **Schema/dicionário de dados** — o que cada coluna significa no contexto do negócio

Serve para: evitar surpresas durante a análise, entender o tamanho do problema e definir o que faz sentido calcular.

### 1.1 Shape
Quantas linhas e colunas existem no dataset.

In [51]:
df

,Unnamed: 0,Income,Kidhome,Teenhome,Recency,MntWines,MntFruits,MntMeatProducts,MntFishProducts,MntSweetProducts,...,education_Graduation,education_Master,education_PhD,MntTotal,MntRegularProds,AcceptedCmpOverall,marital_status,education_level,kids,expenses
0,0,"58,138.00",0,0,58,635,88,546,172,88,...,3.00,NaN,NaN,1529,1441,0,Single,Graduation,0,1529
1,1,"46,344.00",1,1,38,11,1,6,2,1,...,3.00,NaN,NaN,21,15,0,Single,Graduation,2,21
2,2,"71,613.00",0,0,26,426,49,127,111,21,...,3.00,NaN,NaN,734,692,0,Together,Graduation,0,734
3,3,"26,646.00",1,0,26,11,4,20,10,3,...,3.00,NaN,NaN,48,43,0,Together,Graduation,1,48
4,4,"58,293.00",1,0,94,173,43,118,46,27,...,NaN,NaN,5.00,407,392,0,Married,PhD,1,407
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2200,2200,"61,223.00",0,1,46,709,43,182,42,118,...,3.00,NaN,NaN,1094,847,0,Married,Graduation,1,1094
2201,2201,"64,014.00",2,1,56,406,0,30,0,0,...,NaN,NaN,5.00,436,428,1,Together,PhD,3,436
2202,2202,"56,981.00",0,0,91,908,48,217,32,12,...,3.00,NaN,NaN,1217,1193,1,Divorced,Graduation,0,1217
2203,2203,"69,245.00",0,1,8,428,30,214,80,30,...,NaN,4.00,NaN,782,721,0,Together,Master,1,782
2204,2204,"52,869.00",1,1,40,84,3,61,2,1,...,NaN,NaN,5.00,151,130,0,Married,PhD,2,151

### 1.2 Tipos de Variáveis
Numéricas, categóricas, datas, booleanas — define quais análises são aplicáveis a cada coluna.

In [52]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 2205 entries, 0 to 2204
Data columns (total 44 columns):
 #   Column                Non-Null Count  Dtype
---  ------                --------------  -----
 0   Unnamed: 0            2205 non-null   int64
 1   Income                2205 non-null   float64
 2   Kidhome               2205 non-null   int64
 3   Teenhome              2205 non-null   int64
 4   Recency               2205 non-null   int64
 5   MntWines              2205 non-null   int64
 6   MntFruits             2205 non-null   int64
 7   MntMeatProducts       2205 non-null   int64
 8   MntFishProducts       2205 non-null   int64
 9   MntSweetProducts      2205 non-null   int64
 10  MntGoldProds          2205 non-null   int64
 11  NumDealsPurchases     2205 non-null   int64
 12  NumWebPurchases       2205 non-null   int64
 13  NumCatalogPurchases   2205 non-null   int64
 14  NumStorePurchases     2205 non-null   int64
 15  NumWebVisitsMonth     2205 non-null   int64
 16  AcceptedCmp3          2205 non-null   int64
 17  AcceptedCmp4          2205 non-null   int64
 18  AcceptedCmp5          2205 non-null   int64
 19  AcceptedCmp1          2205 non-null   int64
 20  AcceptedCmp2          2205 non-null   int64
 21  Complain              2205 non-null   int64
 22  Z_CostContact         2205 non-null   int64
 23  Z_Revenue             2205 non-null   int64
 24  Response              2205 non-null   int64
 25  Age                   2205 non-null   int64
 26  Customer_Days         2205 non-null   int64
 27  marital_Divorced      230 non-null    float64
 28  marital_Married       854 non-null    float64
 29  marital_Single        477 non-null    float64
 30  marital_Together      568 non-null    float64
 31  marital_Widow         76 non-null     float64
 32  education_2n Cycle    198 non-null    float64
 33  education_Basic       54 non-null     float64
 34  education_Graduation  1113 non-null   float64
 35  education_Master      364 non-null    float64
 36  education_PhD         476 non-null    float64
 37  MntTotal              2205 non-null   int64
 38  MntRegularProds       2205 non-null   int64
 39  AcceptedCmpOverall    2205 non-null   int64
 40  marital_status        2205 non-null   str
 41  education_level       2205 non-null   str
 42  kids                  2205 non-null   int64
 43  expenses              2205 non-null   int64
dtypes: float64(11), int64(31), str(2)
memory usage: 789.5 KB

### 1.3 Primeiras e Últimas Linhas
`head()` e `tail()` para verificar se os dados fazem sentido visualmente antes de qualquer cálculo.

In [53]:
df.head(100)

,Unnamed: 0,Income,Kidhome,Teenhome,Recency,MntWines,MntFruits,MntMeatProducts,MntFishProducts,MntSweetProducts,...,education_Graduation,education_Master,education_PhD,MntTotal,MntRegularProds,AcceptedCmpOverall,marital_status,education_level,kids,expenses
0,0,"58,138.00",0,0,58,635,88,546,172,88,...,3.00,NaN,NaN,1529,1441,0,Single,Graduation,0,1529
1,1,"46,344.00",1,1,38,11,1,6,2,1,...,3.00,NaN,NaN,21,15,0,Single,Graduation,2,21
2,2,"71,613.00",0,0,26,426,49,127,111,21,...,3.00,NaN,NaN,734,692,0,Together,Graduation,0,734
3,3,"26,646.00",1,0,26,11,4,20,10,3,...,3.00,NaN,NaN,48,43,0,Together,Graduation,1,48
4,4,"58,293.00",1,0,94,173,43,118,46,27,...,NaN,NaN,5.00,407,392,0,Married,PhD,1,407
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
95,95,"87,195.00",0,0,35,217,76,690,50,26,...,3.00,NaN,NaN,1059,1021,0,Married,Graduation,0,1059
96,96,"24,594.00",1,0,94,1,3,6,10,0,...,NaN,NaN,NaN,20,11,0,Together,Basic,1,20
97,97,"49,096.00",1,1,15,144,1,32,2,1,...,3.00,NaN,NaN,180,173,0,Married,Graduation,2,180
98,98,"52,413.00",0,2,56,295,106,271,75,98,...,3.00,NaN,NaN,845,780,0,Married,Graduation,2,845
99,99,"38,557.00",1,0,17,76,3,31,4,4,...,3.00,NaN,NaN,118,91,0,Single,Graduation,1,118

In [54]:
df.tail(100)

,Unnamed: 0,Income,Kidhome,Teenhome,Recency,MntWines,MntFruits,MntMeatProducts,MntFishProducts,MntSweetProducts,...,education_Graduation,education_Master,education_PhD,MntTotal,MntRegularProds,AcceptedCmpOverall,marital_status,education_level,kids,expenses
2105,2105,"62,637.00",0,1,76,104,12,48,4,12,...,NaN,4.00,NaN,180,175,0,Divorced,Master,1,180
2106,2106,"29,435.00",1,1,11,70,3,37,4,2,...,NaN,4.00,NaN,116,52,0,Divorced,Master,2,116
2107,2107,"19,346.00",1,0,26,2,0,9,3,6,...,3.00,NaN,NaN,20,18,0,Divorced,Graduation,1,20
2108,2108,"35,788.00",1,1,34,23,2,11,3,1,...,3.00,NaN,NaN,40,36,0,Married,Graduation,2,40
2109,2109,"36,997.00",1,1,72,43,4,12,8,0,...,3.00,NaN,NaN,67,40,0,Divorced,Graduation,2,67
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2200,2200,"61,223.00",0,1,46,709,43,182,42,118,...,3.00,NaN,NaN,1094,847,0,Married,Graduation,1,1094
2201,2201,"64,014.00",2,1,56,406,0,30,0,0,...,NaN,NaN,5.00,436,428,1,Together,PhD,3,436
2202,2202,"56,981.00",0,0,91,908,48,217,32,12,...,3.00,NaN,NaN,1217,1193,1,Divorced,Graduation,0,1217
2203,2203,"69,245.00",0,1,8,428,30,214,80,30,...,NaN,4.00,NaN,782,721,0,Together,Master,1,782
2204,2204,"52,869.00",1,1,40,84,3,61,2,1,...,NaN,NaN,5.00,151,130,0,Married,PhD,2,151

### 1.4 Schema / Dicionário de Dados
O que cada coluna representa no contexto do negócio — essencial para interpretar os resultados corretamente.

In [55]:
# @title Leitura do conjunto e criação do dicionário de dados

df_dict = pd.DataFrame([
    # Perfil do cliente
    {
        "variavel": "Income",
        "traducao": "Renda",
        "descricao": "Renda anual do cliente.",
        "tipo": "Quantitativa",
        "subtipo": "Contínua"
    },
    {
        "variavel": "Age",
        "traducao": "Idade",
        "descricao": "Idade do cliente em anos.",
        "tipo": "Quantitativa",
        "subtipo": "Discreta"
    },
    {
        "variavel": "Customer_Days",
        "traducao": "Dias como Cliente",
        "descricao": "Número de dias desde o cadastro do cliente.",
        "tipo": "Quantitativa",
        "subtipo": "Discreta"
    },
    {
        "variavel": "marital_status",
        "traducao": "Estado Civil",
        "descricao": "Estado civil do cliente (Divorced, Married, Single, Together, Widow).",
        "tipo": "Qualitativa",
        "subtipo": "Nominal"
    },
    {
        "variavel": "education_level",
        "traducao": "Nível de Escolaridade",
        "descricao": "Nível de escolaridade do cliente (Basic, 2n Cycle, Graduation, Master, PhD).",
        "tipo": "Qualitativa",
        "subtipo": "Ordinal"
    },
    {
        "variavel": "Kidhome",
        "traducao": "Crianças em Casa",
        "descricao": "Número de crianças residindo na casa do cliente.",
        "tipo": "Quantitativa",
        "subtipo": "Discreta"
    },
    {
        "variavel": "Teenhome",
        "traducao": "Adolescentes em Casa",
        "descricao": "Número de adolescentes residindo na casa do cliente.",
        "tipo": "Quantitativa",
        "subtipo": "Discreta"
    },
    {
        "variavel": "kids",
        "traducao": "Total de Filhos",
        "descricao": "Total de filhos em casa (Kidhome + Teenhome).",
        "tipo": "Quantitativa",
        "subtipo": "Discreta"
    },
    # Gastos por categoria
    {
        "variavel": "MntWines",
        "traducao": "Gasto com Vinhos",
        "descricao": "Valor gasto em vinhos nos últimos 2 anos.",
        "tipo": "Quantitativa",
        "subtipo": "Contínua"
    },
    {
        "variavel": "MntFruits",
        "traducao": "Gasto com Frutas",
        "descricao": "Valor gasto em frutas nos últimos 2 anos.",
        "tipo": "Quantitativa",
        "subtipo": "Contínua"
    },
    {
        "variavel": "MntMeatProducts",
        "traducao": "Gasto com Carnes",
        "descricao": "Valor gasto em carnes nos últimos 2 anos.",
        "tipo": "Quantitativa",
        "subtipo": "Contínua"
    },
    {
        "variavel": "MntFishProducts",
        "traducao": "Gasto com Peixes",
        "descricao": "Valor gasto em peixes nos últimos 2 anos.",
        "tipo": "Quantitativa",
        "subtipo": "Contínua"
    },
    {
        "variavel": "MntSweetProducts",
        "traducao": "Gasto com Doces",
        "descricao": "Valor gasto em doces nos últimos 2 anos.",
        "tipo": "Quantitativa",
        "subtipo": "Contínua"
    },
    {
        "variavel": "MntGoldProds",
        "traducao": "Gasto com Produtos Premium",
        "descricao": "Valor gasto em produtos premium nos últimos 2 anos.",
        "tipo": "Quantitativa",
        "subtipo": "Contínua"
    },
    {
        "variavel": "MntRegularProds",
        "traducao": "Gasto com Produtos Regulares",
        "descricao": "Valor gasto em produtos regulares (MntTotal - MntGoldProds).",
        "tipo": "Quantitativa",
        "subtipo": "Contínua"
    },
    {
        "variavel": "MntTotal",
        "traducao": "Gasto Total",
        "descricao": "Valor total gasto em todos os produtos nos últimos 2 anos.",
        "tipo": "Quantitativa",
        "subtipo": "Contínua"
    },
    {
        "variavel": "expenses",
        "traducao": "Despesas",
        "descricao": "Valor total gasto (idêntico a MntTotal).",
        "tipo": "Quantitativa",
        "subtipo": "Contínua"
    },
    # Canais de compra
    {
        "variavel": "Recency",
        "traducao": "Recência",
        "descricao": "Número de dias desde a última compra do cliente.",
        "tipo": "Quantitativa",
        "subtipo": "Discreta"
    },
    {
        "variavel": "NumDealsPurchases",
        "traducao": "Compras com Desconto",
        "descricao": "Número de compras realizadas com desconto.",
        "tipo": "Quantitativa",
        "subtipo": "Discreta"
    },
    {
        "variavel": "NumWebPurchases",
        "traducao": "Compras pelo Site",
        "descricao": "Número de compras realizadas pelo site.",
        "tipo": "Quantitativa",
        "subtipo": "Discreta"
    },
    {
        "variavel": "NumCatalogPurchases",
        "traducao": "Compras por Catálogo",
        "descricao": "Número de compras realizadas por catálogo.",
        "tipo": "Quantitativa",
        "subtipo": "Discreta"
    },
    {
        "variavel": "NumStorePurchases",
        "traducao": "Compras em Loja Física",
        "descricao": "Número de compras realizadas em loja física.",
        "tipo": "Quantitativa",
        "subtipo": "Discreta"
    },
    {
        "variavel": "NumWebVisitsMonth",
        "traducao": "Visitas ao Site no Mês",
        "descricao": "Número de visitas ao site no último mês.",
        "tipo": "Quantitativa",
        "subtipo": "Discreta"
    },
    # Campanhas
    {
        "variavel": "AcceptedCmp1",
        "traducao": "Aceitou Campanha 1",
        "descricao": "Indica se o cliente aceitou a oferta da 1ª campanha (1=Sim, 0=Não).",
        "tipo": "Qualitativa",
        "subtipo": "Nominal"
    },
    {
        "variavel": "AcceptedCmp2",
        "traducao": "Aceitou Campanha 2",
        "descricao": "Indica se o cliente aceitou a oferta da 2ª campanha (1=Sim, 0=Não).",
        "tipo": "Qualitativa",
        "subtipo": "Nominal"
    },
    {
        "variavel": "AcceptedCmp3",
        "traducao": "Aceitou Campanha 3",
        "descricao": "Indica se o cliente aceitou a oferta da 3ª campanha (1=Sim, 0=Não).",
        "tipo": "Qualitativa",
        "subtipo": "Nominal"
    },
    {
        "variavel": "AcceptedCmp4",
        "traducao": "Aceitou Campanha 4",
        "descricao": "Indica se o cliente aceitou a oferta da 4ª campanha (1=Sim, 0=Não).",
        "tipo": "Qualitativa",
        "subtipo": "Nominal"
    },
    {
        "variavel": "AcceptedCmp5",
        "traducao": "Aceitou Campanha 5",
        "descricao": "Indica se o cliente aceitou a oferta da 5ª campanha (1=Sim, 0=Não).",
        "tipo": "Qualitativa",
        "subtipo": "Nominal"
    },
    {
        "variavel": "AcceptedCmpOverall",
        "traducao": "Total de Campanhas Aceitas",
        "descricao": "Total de campanhas aceitas pelo cliente (excluindo a última).",
        "tipo": "Quantitativa",
        "subtipo": "Discreta"
    },
    {
        "variavel": "Response",
        "traducao": "Resposta (Variável-Alvo)",
        "descricao": "Variável-alvo: indica se o cliente aceitou a última campanha (1=Sim, 0=Não).",
        "tipo": "Qualitativa",
        "subtipo": "Nominal"
    },
    {
        "variavel": "Complain",
        "traducao": "Reclamação",
        "descricao": "Indica se o cliente fez alguma reclamação nos últimos 2 anos (1=Sim, 0=Não).",
        "tipo": "Qualitativa",
        "subtipo": "Nominal"
    },
    # Custo/Receita
    {
        "variavel": "Z_CostContact",
        "traducao": "Custo de Contato",
        "descricao": "Custo fixo de contato por cliente (constante = 3).",
        "tipo": "Quantitativa",
        "subtipo": "Discreta"
    },
    {
        "variavel": "Z_Revenue",
        "traducao": "Receita por Conversão",
        "descricao": "Receita fixa gerada por conversão de campanha (constante = 11).",
        "tipo": "Quantitativa",
        "subtipo": "Discreta"
    },
    # Variáveis encoded
    {
        "variavel": "marital_Divorced",
        "traducao": "Estado Civil: Divorciado",
        "descricao": "Encoded de marital_status: código 1 se divorciado, NaN caso contrário.",
        "tipo": "Qualitativa",
        "subtipo": "Nominal"
    },
    {
        "variavel": "marital_Widow",
        "traducao": "Estado Civil: Viúvo",
        "descricao": "Encoded de marital_status: código 2 se viúvo, NaN caso contrário.",
        "tipo": "Qualitativa",
        "subtipo": "Nominal"
    },
    {
        "variavel": "marital_Together",
        "traducao": "Estado Civil: União Estável",
        "descricao": "Encoded de marital_status: código 3 se em união estável, NaN caso contrário.",
        "tipo": "Qualitativa",
        "subtipo": "Nominal"
    },
    {
        "variavel": "marital_Single",
        "traducao": "Estado Civil: Solteiro",
        "descricao": "Encoded de marital_status: código 4 se solteiro, NaN caso contrário.",
        "tipo": "Qualitativa",
        "subtipo": "Nominal"
    },
    {
        "variavel": "marital_Married",
        "traducao": "Estado Civil: Casado",
        "descricao": "Encoded de marital_status: código 5 se casado, NaN caso contrário.",
        "tipo": "Qualitativa",
        "subtipo": "Nominal"
    },
    {
        "variavel": "education_2n Cycle",
        "traducao": "Escolaridade: 2º Ciclo",
        "descricao": "Encoded de education_level: código 1 se 2º ciclo, NaN caso contrário.",
        "tipo": "Qualitativa",
        "subtipo": "Ordinal"
    },
    {
        "variavel": "education_Basic",
        "traducao": "Escolaridade: Ensino Básico",
        "descricao": "Encoded de education_level: código 2 se ensino básico, NaN caso contrário.",
        "tipo": "Qualitativa",
        "subtipo": "Ordinal"
    },
    {
        "variavel": "education_Graduation",
        "traducao": "Escolaridade: Graduação",
        "descricao": "Encoded de education_level: código 3 se graduação, NaN caso contrário.",
        "tipo": "Qualitativa",
        "subtipo": "Ordinal"
    },
    {
        "variavel": "education_Master",
        "traducao": "Escolaridade: Mestrado",
        "descricao": "Encoded de education_level: código 4 se mestrado, NaN caso contrário.",
        "tipo": "Qualitativa",
        "subtipo": "Ordinal"
    },
    {
        "variavel": "education_PhD",
        "traducao": "Escolaridade: Doutorado",
        "descricao": "Encoded de education_level: código 5 se doutorado, NaN caso contrário.",
        "tipo": "Qualitativa",
        "subtipo": "Ordinal"
    },
])


df_dict

,variavel,traducao,descricao,tipo,subtipo
0,Income,Renda,Renda anual do cliente.,Quantitativa,Contínua
1,Age,Idade,Idade do cliente em anos.,Quantitativa,Discreta
2,Customer_Days,Dias como Cliente,Número de dias desde o cadastro do cliente.,Quantitativa,Discreta
3,marital_status,Estado Civil,"Estado civil do cliente (Divorced, Married, Si...",Qualitativa,Nominal
4,education_level,Nível de Escolaridade,"Nível de escolaridade do cliente (Basic, 2n Cy...",Qualitativa,Ordinal
5,Kidhome,Crianças em Casa,Número de crianças residindo na casa do cliente.,Quantitativa,Discreta
6,Teenhome,Adolescentes em Casa,Número de adolescentes residindo na casa do cl...,Quantitativa,Discreta
7,kids,Total de Filhos,Total de filhos em casa (Kidhome + Teenhome).,Quantitativa,Discreta
8,MntWines,Gasto com Vinhos,Valor gasto em vinhos nos últimos 2 anos.,Quantitativa,Contínua
9,MntFruits,Gasto com Frutas,Valor gasto em frutas nos últimos 2 anos.,Quantitativa,Contínua
10,MntMeatProducts,Gasto com Carnes,Valor gasto em carnes nos últimos 2 anos.,Quantitativa,Contínua
11,MntFishProducts,Gasto com Peixes,Valor gasto em peixes nos últimos 2 anos.,Quantitativa,Contínua
12,MntSweetProducts,Gasto com Doces,Valor gasto em doces nos últimos 2 anos.,Quantitativa,Contínua
13,MntGoldProds,Gasto com Produtos Premium,Valor gasto em produtos premium nos últimos 2 ...,Quantitativa,Contínua
14,MntRegularProds,Gasto com Produtos Regulares,Valor gasto em produtos regulares (MntTotal - ...,Quantitativa,Contínua
15,MntTotal,Gasto Total,Valor total gasto em todos os produtos nos últ...,Quantitativa,Contínua
16,expenses,Despesas,Valor total gasto (idêntico a MntTotal).,Quantitativa,Contínua
17,Recency,Recência,Número de dias desde a última compra do cliente.,Quantitativa,Discreta
18,NumDealsPurchases,Compras com Desconto,Número de compras realizadas com desconto.,Quantitativa,Discreta
19,NumWebPurchases,Compras pelo Site,Número de compras realizadas pelo site.,Quantitativa,Discreta
20,NumCatalogPurchases,Compras por Catálogo,Número de compras realizadas por catálogo.,Quantitativa,Discreta
21,NumStorePurchases,Compras em Loja Física,Número de compras realizadas em loja física.,Quantitativa,Discreta
22,NumWebVisitsMonth,Visitas ao Site no Mês,Número de visitas ao site no último mês.,Quantitativa,Discreta
23,AcceptedCmp1,Aceitou Campanha 1,Indica se o cliente aceitou a oferta da 1ª cam...,Qualitativa,Nominal
24,AcceptedCmp2,Aceitou Campanha 2,Indica se o cliente aceitou a oferta da 2ª cam...,Qualitativa,Nominal
25,AcceptedCmp3,Aceitou Campanha 3,Indica se o cliente aceitou a oferta da 3ª cam...,Qualitativa,Nominal
26,AcceptedCmp4,Aceitou Campanha 4,Indica se o cliente aceitou a oferta da 4ª cam...,Qualitativa,Nominal
27,AcceptedCmp5,Aceitou Campanha 5,Indica se o cliente aceitou a oferta da 5ª cam...,Qualitativa,Nominal
28,AcceptedCmpOverall,Total de Campanhas Aceitas,Total de campanhas aceitas pelo cliente (exclu...,Quantitativa,Discreta
29,Response,Resposta (Variável-Alvo),Variável-alvo: indica se o cliente aceitou a ú...,Qualitativa,Nominal
30,Complain,Reclamação,Indica se o cliente fez alguma reclamação nos ...,Qualitativa,Nominal
31,Z_CostContact,Custo de Contato,Custo fixo de contato por cliente (constante =...,Quantitativa,Discreta
32,Z_Revenue,Receita por Conversão,Receita fixa gerada por conversão de campanha ...,Quantitativa,Discreta
33,marital_Divorced,Estado Civil: Divorciado,Encoded de marital_status: código 1 se divorci...,Qualitativa,Nominal
34,marital_Widow,Estado Civil: Viúvo,"Encoded de marital_status: código 2 se viúvo, ...",Qualitativa,Nominal
35,marital_Together,Estado Civil: União Estável,Encoded de marital_status: código 3 se em uniã...,Qualitativa,Nominal
36,marital_Single,Estado Civil: Solteiro,Encoded de marital_status: código 4 se solteir...,Qualitativa,Nominal
37,marital_Married,Estado Civil: Casado,"Encoded de marital_status: código 5 se casado,...",Qualitativa,Nominal
38,education_2n Cycle,Escolaridade: 2º Ciclo,Encoded de education_level: código 1 se 2º cic...,Qualitativa,Ordinal
39,education_Basic,Escolaridade: Ensino Básico,Encoded de education_level: código 2 se ensino...,Qualitativa,Ordinal
40,education_Graduation,Escolaridade: Graduação,Encoded de education_level: código 3 se gradua...,Qualitativa,Ordinal
41,education_Master,Escolaridade: Mestrado,Encoded de education_level: código 4 se mestra...,Qualitativa,Ordinal
42,education_PhD,Escolaridade: Doutorado,Encoded de education_level: código 5 se doutor...,Qualitativa,Ordinal


---

**2.205 registros · 43 variáveis** — Dataset de campanha de marketing do iFood

**Perfil do Cliente**

| Variável | Tipo | Valores | Descrição |
|---|---|---|---|
| `Income` | float | 1.730 – 113.734 | Renda anual do cliente |
| `Age` | int | 24 – 80 | Idade do cliente (anos) |
| `Customer_Days` | int | 2.159 – 2.858 | Dias desde o cadastro do cliente |
| `marital_status` | str | Divorced, Married, Single, Together, Widow | Estado civil |
| `education_level` | str | Basic, 2n Cycle, Graduation, Master, PhD | Nível de escolaridade |
| `Kidhome` | int | 0, 1, 2 | Nº de crianças em casa |
| `Teenhome` | int | 0, 1, 2 | Nº de adolescentes em casa |
| `kids` | int | 0 – 3 | Total de filhos em casa (`Kidhome + Teenhome`) |

**Gastos por Categoria (últimos 2 anos)**

| Variável | Tipo | Valores | Descrição |
|---|---|---|---|
| `MntWines` | int | 0 – 1.493 | Gasto com vinhos |
| `MntFruits` | int | 0 – 199 | Gasto com frutas |
| `MntMeatProducts` | int | 0 – 1.725 | Gasto com carnes |
| `MntFishProducts` | int | 0 – 259 | Gasto com peixes |
| `MntSweetProducts` | int | 0 – 262 | Gasto com doces |
| `MntGoldProds` | int | 0 – 321 | Gasto com produtos premium ("ouro") |
| `MntRegularProds` | int | — | Gasto em produtos regulares (`MntTotal - MntGoldProds`) |
| `MntTotal` | int | 4 – 2.491 | Gasto total em todos os produtos |
| `expenses` | int | 4 – 2.491 | Idêntico a `MntTotal` (coluna duplicada) |

**Canais de Compra**

| Variável | Tipo | Valores | Descrição |
|---|---|---|---|
| `NumDealsPurchases` | int | 0 – 15 | Nº de compras com desconto |
| `NumWebPurchases` | int | 0 – 27 | Nº de compras pelo site |
| `NumCatalogPurchases` | int | 0 – 28 | Nº de compras por catálogo |
| `NumStorePurchases` | int | 0 – 13 | Nº de compras em loja física |
| `NumWebVisitsMonth` | int | 0 – 20 | Nº de visitas ao site no último mês |
| `Recency` | int | 0 – 99 | Dias desde a última compra |

**Campanhas de Marketing**

| Variável | Tipo | Valores | Descrição |
|---|---|---|---|
| `AcceptedCmp1` | binário | 0, 1 | Aceitou oferta da 1ª campanha |
| `AcceptedCmp2` | binário | 0, 1 | Aceitou oferta da 2ª campanha |
| `AcceptedCmp3` | binário | 0, 1 | Aceitou oferta da 3ª campanha |
| `AcceptedCmp4` | binário | 0, 1 | Aceitou oferta da 4ª campanha |
| `AcceptedCmp5` | binário | 0, 1 | Aceitou oferta da 5ª campanha |
| `AcceptedCmpOverall` | int | 0 – 4 | Total de campanhas aceitas (excluindo a última) |
| `Response` | binário | 0, 1 | **Variável-alvo:** aceitou a última campanha (1=Sim) |
| `Complain` | binário | 0, 1 | Fez reclamação nos últimos 2 anos (1=Sim) |

**Variáveis de Custo/Receita (constantes)**

| Variável | Tipo | Valor fixo | Descrição |
|---|---|---|---|
| `Z_CostContact` | int | 3 | Custo fixo de contato por cliente |
| `Z_Revenue` | int | 11 | Receita fixa gerada por conversão |

Essas duas variáveis são constantes em todo o dataset — provavelmente usadas para calcular o lucro de uma campanha: `Lucro = Response × Z_Revenue - Z_CostContact`.

**Variáveis Encoded (derivadas de `marital_status` e `education_level`)**

Colunas geradas por label encoding — contêm o código numérico da categoria quando o cliente pertence a ela, `NaN` caso contrário. São redundantes com as colunas originais.

| Variável | Código |
|---|---|
| `marital_Divorced` | 1 |
| `marital_Widow` | 2 |
| `marital_Together` | 3 |
| `marital_Single` | 4 |
| `marital_Married` | 5 |
| `education_2n Cycle` | 1 |
| `education_Basic` | 2 |
| `education_Graduation` | 3 |
| `education_Master` | 4 |
| `education_PhD` | 5 |

**Observações**

- `expenses` e `MntTotal` são idênticas — pode remover uma.
- As colunas `marital_*` e `education_*` numéricas são redundantes com `marital_status` e `education_level`.
- `Z_CostContact` e `Z_Revenue` são constantes e não têm poder preditivo.
- A variável-alvo (`Response`) tem ~15% de taxa de aceitação — dataset desbalanceado.

### 1.5 Traduzindo Variáveis
Renomeia as colunas do DataFrame para português usando o dicionário de dados criado em 1.4.

In [56]:
mapa_colunas = df_dict.set_index("variavel")["traducao"].to_dict()
df = df.rename(columns=mapa_colunas)

df.columns.tolist()

['Unnamed: 0',
 'Renda',
 'Crianças em Casa',
 'Adolescentes em Casa',
 'Recência',
 'Gasto com Vinhos',
 'Gasto com Frutas',
 'Gasto com Carnes',
 'Gasto com Peixes',
 'Gasto com Doces',
 'Gasto com Produtos Premium',
 'Compras com Desconto',
 'Compras pelo Site',
 'Compras por Catálogo',
 'Compras em Loja Física',
 'Visitas ao Site no Mês',
 'Aceitou Campanha 3',
 'Aceitou Campanha 4',
 'Aceitou Campanha 5',
 'Aceitou Campanha 1',
 'Aceitou Campanha 2',
 'Reclamação',
 'Custo de Contato',
 'Receita por Conversão',
 'Resposta (Variável-Alvo)',
 'Idade',
 'Dias como Cliente',
 'Estado Civil: Divorciado',
 'Estado Civil: Casado',
 'Estado Civil: Solteiro',
 'Estado Civil: União Estável',
 'Estado Civil: Viúvo',
 'Escolaridade: 2º Ciclo',
 'Escolaridade: Ensino Básico',
 'Escolaridade: Graduação',
 'Escolaridade: Mestrado',
 'Escolaridade: Doutorado',
 'Gasto Total',
 'Gasto com Produtos Regulares',
 'Total de Campanhas Aceitas',
 'Estado Civil',
 'Nível de Escolaridade',
 'Total de Filhos',
 'Despesas']

---
## **2. Qualidade dos Dados**

- **Valores ausentes (missing values)** — quantidade e percentual por coluna; padrão de ausência (aleatório ou sistemático?)
- **Duplicatas** — linhas idênticas ou quase idênticas
- **Inconsistências** — valores impossíveis (ex: idade negativa, data futura em campo de nascimento)
- **Outliers brutos** — valores absurdos que indicam erro de coleta (diferente de outlier estatístico)
- **Cardinalidade de categóricas** — colunas com milhares de categorias únicas podem ser IDs disfarçados

Serve para: não construir análises sobre dados corrompidos. Lixo entra, lixo sai.

### 2.1 Valores Ausentes (Missing Values)
Quantidade e percentual por coluna; identificar se a ausência é aleatória ou sistemática orienta a estratégia de imputação.

In [57]:
visao_geral = df.info()
visao_geral

<class 'pandas.DataFrame'>
RangeIndex: 2205 entries, 0 to 2204
Data columns (total 44 columns):
 #   Column                        Non-Null Count  Dtype
---  ------                        --------------  -----
 0   Unnamed: 0                    2205 non-null   int64
 1   Renda                         2205 non-null   float64
 2   Crianças em Casa              2205 non-null   int64
 3   Adolescentes em Casa          2205 non-null   int64
 4   Recência                      2205 non-null   int64
 5   Gasto com Vinhos              2205 non-null   int64
 6   Gasto com Frutas              2205 non-null   int64
 7   Gasto com Carnes              2205 non-null   int64
 8   Gasto com Peixes              2205 non-null   int64
 9   Gasto com Doces               2205 non-null   int64
 10  Gasto com Produtos Premium    2205 non-null   int64
 11  Compras com Desconto          2205 non-null   int64
 12  Compras pelo Site             2205 non-null   int64
 13  Compras por Catálogo          2205 non-null   int64
 14  Compras em Loja Física        2205 non-null   int64
 15  Visitas ao Site no Mês        2205 non-null   int64
 16  Aceitou Campanha 3            2205 non-null   int64
 17  Aceitou Campanha 4            2205 non-null   int64
 18  Aceitou Campanha 5            2205 non-null   int64
 19  Aceitou Campanha 1            2205 non-null   int64
 20  Aceitou Campanha 2            2205 non-null   int64
 21  Reclamação                    2205 non-null   int64
 22  Custo de Contato              2205 non-null   int64
 23  Receita por Conversão         2205 non-null   int64
 24  Resposta (Variável-Alvo)      2205 non-null   int64
 25  Idade                         2205 non-null   int64
 26  Dias como Cliente             2205 non-null   int64
 27  Estado Civil: Divorciado      230 non-null    float64
 28  Estado Civil: Casado          854 non-null    float64
 29  Estado Civil: Solteiro        477 non-null    float64
 30  Estado Civil: União Estável   568 non-null    float64
 31  Estado Civil: Viúvo           76 non-null     float64
 32  Escolaridade: 2º Ciclo        198 non-null    float64
 33  Escolaridade: Ensino Básico   54 non-null     float64
 34  Escolaridade: Graduação       1113 non-null   float64
 35  Escolaridade: Mestrado        364 non-null    float64
 36  Escolaridade: Doutorado       476 non-null    float64
 37  Gasto Total                   2205 non-null   int64
 38  Gasto com Produtos Regulares  2205 non-null   int64
 39  Total de Campanhas Aceitas    2205 non-null   int64
 40  Estado Civil                  2205 non-null   str
 41  Nível de Escolaridade         2205 non-null   str
 42  Total de Filhos               2205 non-null   int64
 43  Despesas                      2205 non-null   int64
dtypes: float64(11), int64(31), str(2)
memory usage: 789.5 KB

> Aplicando o 'df.info()', constatamos que a presente base de dados não tem nenhum valor nulo, pois as mesmas quantidades de dados que temos em cada variável corresponde ao número de valores em cada linha, que é 2025.

### 2.2 Duplicatas
Linhas idênticas ou quase idênticas que distorcem distribuições e inflam métricas de frequência.

In [58]:
print(f"Duplicatas: {df.duplicated().sum()}")

Duplicatas: 0

> Constatamos também que não existem dados duplicados na nosssa base de dados.

### 2.3 Inconsistências
Valores impossíveis, como idade negativa ou datas futuras em campos de nascimento.

In [59]:
# Estatísticas básicas — procurando por min/max absurdos
df.describe()

,Unnamed: 0,Renda,Crianças em Casa,Adolescentes em Casa,Recência,Gasto com Vinhos,Gasto com Frutas,Gasto com Carnes,Gasto com Peixes,Gasto com Doces,...,Escolaridade: 2º Ciclo,Escolaridade: Ensino Básico,Escolaridade: Graduação,Escolaridade: Mestrado,Escolaridade: Doutorado,Gasto Total,Gasto com Produtos Regulares,Total de Campanhas Aceitas,Total de Filhos,Despesas
count,"2,205.00","2,205.00","2,205.00","2,205.00","2,205.00","2,205.00","2,205.00","2,205.00","2,205.00","2,205.00",...,198.00,54.00,"1,113.00",364.00,476.00,"2,205.00","2,205.00","2,205.00","2,205.00","2,205.00"
mean,"1,102.00","51,622.09",0.44,0.51,49.01,306.16,26.40,165.31,37.76,27.13,...,1.00,2.00,3.00,4.00,5.00,562.76,518.71,0.30,0.95,562.76
std,636.67,"20,713.06",0.54,0.54,28.93,337.49,39.78,217.78,54.82,41.13,...,0.00,0.00,0.00,0.00,0.00,575.94,553.85,0.68,0.75,575.94
min,0.00,"1,730.00",0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,...,1.00,2.00,3.00,4.00,5.00,4.00,-283.00,0.00,0.00,4.00
25%,551.00,"35,196.00",0.00,0.00,24.00,24.00,2.00,16.00,3.00,1.00,...,1.00,2.00,3.00,4.00,5.00,56.00,42.00,0.00,0.00,56.00
50%,"1,102.00","51,287.00",0.00,0.00,49.00,178.00,8.00,68.00,12.00,8.00,...,1.00,2.00,3.00,4.00,5.00,343.00,288.00,0.00,1.00,343.00
75%,"1,653.00","68,281.00",1.00,1.00,74.00,507.00,33.00,232.00,50.00,34.00,...,1.00,2.00,3.00,4.00,5.00,964.00,884.00,0.00,1.00,964.00
max,"2,204.00","113,734.00",2.00,2.00,99.00,"1,493.00",199.00,"1,725.00",259.00,262.00,...,1.00,2.00,3.00,4.00,5.00,"2,491.00","2,458.00",4.00,3.00,"2,491.00"

In [60]:
# 1. Idades impossíveis
df[~df["Idade"].between(18, 100)]

Empty DataFrame
Columns: [Unnamed: 0, Renda, Crianças em Casa, Adolescentes em Casa, Recência, Gasto com Vinhos, Gasto com Frutas, Gasto com Carnes, Gasto com Peixes, Gasto com Doces, Gasto com Produtos Premium, Compras com Desconto, Compras pelo Site, Compras por Catálogo, Compras em Loja Física, Visitas ao Site no Mês, Aceitou Campanha 3, Aceitou Campanha 4, Aceitou Campanha 5, Aceitou Campanha 1, Aceitou Campanha 2, Reclamação, Custo de Contato, Receita por Conversão, Resposta (Variável-Alvo), Idade, Dias como Cliente, Estado Civil: Divorciado, Estado Civil: Casado, Estado Civil: Solteiro, Estado Civil: União Estável, Estado Civil: Viúvo, Escolaridade: 2º Ciclo, Escolaridade: Ensino Básico, Escolaridade: Graduação, Escolaridade: Mestrado, Escolaridade: Doutorado, Gasto Total, Gasto com Produtos Regulares, Total de Campanhas Aceitas, Estado Civil, Nível de Escolaridade, Total de Filhos, Despesas]
Index: []

[0 rows x 44 columns]

In [61]:
# 2. Renda negativa ou absurda
df[df["Renda"] <= 0]

Empty DataFrame
Columns: [Unnamed: 0, Renda, Crianças em Casa, Adolescentes em Casa, Recência, Gasto com Vinhos, Gasto com Frutas, Gasto com Carnes, Gasto com Peixes, Gasto com Doces, Gasto com Produtos Premium, Compras com Desconto, Compras pelo Site, Compras por Catálogo, Compras em Loja Física, Visitas ao Site no Mês, Aceitou Campanha 3, Aceitou Campanha 4, Aceitou Campanha 5, Aceitou Campanha 1, Aceitou Campanha 2, Reclamação, Custo de Contato, Receita por Conversão, Resposta (Variável-Alvo), Idade, Dias como Cliente, Estado Civil: Divorciado, Estado Civil: Casado, Estado Civil: Solteiro, Estado Civil: União Estável, Estado Civil: Viúvo, Escolaridade: 2º Ciclo, Escolaridade: Ensino Básico, Escolaridade: Graduação, Escolaridade: Mestrado, Escolaridade: Doutorado, Gasto Total, Gasto com Produtos Regulares, Total de Campanhas Aceitas, Estado Civil, Nível de Escolaridade, Total de Filhos, Despesas]
Index: []

[0 rows x 44 columns]

In [62]:
# 3. Gastos negativos — MntRegularProds tem mínimo de -283 (vimos no describe)
df[df["Gasto com Produtos Regulares"] < 0]

,Unnamed: 0,Renda,Crianças em Casa,Adolescentes em Casa,Recência,Gasto com Vinhos,Gasto com Frutas,Gasto com Carnes,Gasto com Peixes,Gasto com Doces,...,Escolaridade: Graduação,Escolaridade: Mestrado,Escolaridade: Doutorado,Gasto Total,Gasto com Produtos Regulares,Total de Campanhas Aceitas,Estado Civil,Nível de Escolaridade,Total de Filhos,Despesas
1307,1307,"6,560.00",0,0,2,67,11,26,4,3,...,NaN,4.00,NaN,111,-151,0,Single,Master,0,111
1780,1780,"7,144.00",0,2,92,81,4,33,5,2,...,NaN,NaN,5.00,125,-166,0,Single,PhD,2,125
1949,1949,"4,428.00",0,1,0,16,4,12,2,4,...,3.00,NaN,NaN,38,-283,0,Married,Graduation,1,38

In [63]:
# 4. Variações nas categorias
df["Estado Civil"].value_counts()
df["Nível de Escolaridade"].value_counts()

Nível de Escolaridade
Graduation    1113
PhD            476
Master         364
2n Cycle       198
Basic           54
Name: count, dtype: int64

In [64]:
# 5. Total de filhos inconsistente com os subtotais
df[(df["Total de Filhos"]) != (df["Crianças em Casa"] + df["Adolescentes em Casa"])]

Empty DataFrame
Columns: [Unnamed: 0, Renda, Crianças em Casa, Adolescentes em Casa, Recência, Gasto com Vinhos, Gasto com Frutas, Gasto com Carnes, Gasto com Peixes, Gasto com Doces, Gasto com Produtos Premium, Compras com Desconto, Compras pelo Site, Compras por Catálogo, Compras em Loja Física, Visitas ao Site no Mês, Aceitou Campanha 3, Aceitou Campanha 4, Aceitou Campanha 5, Aceitou Campanha 1, Aceitou Campanha 2, Reclamação, Custo de Contato, Receita por Conversão, Resposta (Variável-Alvo), Idade, Dias como Cliente, Estado Civil: Divorciado, Estado Civil: Casado, Estado Civil: Solteiro, Estado Civil: União Estável, Estado Civil: Viúvo, Escolaridade: 2º Ciclo, Escolaridade: Ensino Básico, Escolaridade: Graduação, Escolaridade: Mestrado, Escolaridade: Doutorado, Gasto Total, Gasto com Produtos Regulares, Total de Campanhas Aceitas, Estado Civil, Nível de Escolaridade, Total de Filhos, Despesas]
Index: []

[0 rows x 44 columns]

> Diante do que foi analisado, a única incosistência encontrada foi a de **Gastos Negativos**. Iremos tratá-la agora.

In [65]:
# Quantas linhas têm gasto negativo?
mask_neg = df["Gasto com Produtos Regulares"] < 0
print(f"Linhas com gasto negativo: {mask_neg.sum()}")

# Ver as linhas problemáticas
df[mask_neg]

Linhas com gasto negativo: 3

,Unnamed: 0,Renda,Crianças em Casa,Adolescentes em Casa,Recência,Gasto com Vinhos,Gasto com Frutas,Gasto com Carnes,Gasto com Peixes,Gasto com Doces,...,Escolaridade: Graduação,Escolaridade: Mestrado,Escolaridade: Doutorado,Gasto Total,Gasto com Produtos Regulares,Total de Campanhas Aceitas,Estado Civil,Nível de Escolaridade,Total de Filhos,Despesas
1307,1307,"6,560.00",0,0,2,67,11,26,4,3,...,NaN,4.00,NaN,111,-151,0,Single,Master,0,111
1780,1780,"7,144.00",0,2,92,81,4,33,5,2,...,NaN,NaN,5.00,125,-166,0,Single,PhD,2,125
1949,1949,"4,428.00",0,1,0,16,4,12,2,4,...,3.00,NaN,NaN,38,-283,0,Married,Graduation,1,38

In [66]:
# Ver as linhas onde o gasto premium é maior que o gasto total
mask_neg = df["Gasto com Produtos Regulares"] < 0
df[mask_neg][["Gasto Total", "Gasto com Produtos Premium", "Gasto com Produtos Regulares"]]

      Gasto Total  Gasto com Produtos Premium  Gasto com Produtos Regulares
1307          111                         262                          -151
1780          125                         291                          -166
1949           38                         321                          -283

In [67]:
df.loc[df["Gasto com Produtos Regulares"] < 0, "Gasto com Produtos Regulares"] = 0

In [68]:
print(df["Gasto com Produtos Regulares"].min())  # deve ser >= 0
df[df["Gasto com Produtos Regulares"] < 0]       # deve retornar vazio

0

Empty DataFrame
Columns: [Unnamed: 0, Renda, Crianças em Casa, Adolescentes em Casa, Recência, Gasto com Vinhos, Gasto com Frutas, Gasto com Carnes, Gasto com Peixes, Gasto com Doces, Gasto com Produtos Premium, Compras com Desconto, Compras pelo Site, Compras por Catálogo, Compras em Loja Física, Visitas ao Site no Mês, Aceitou Campanha 3, Aceitou Campanha 4, Aceitou Campanha 5, Aceitou Campanha 1, Aceitou Campanha 2, Reclamação, Custo de Contato, Receita por Conversão, Resposta (Variável-Alvo), Idade, Dias como Cliente, Estado Civil: Divorciado, Estado Civil: Casado, Estado Civil: Solteiro, Estado Civil: União Estável, Estado Civil: Viúvo, Escolaridade: 2º Ciclo, Escolaridade: Ensino Básico, Escolaridade: Graduação, Escolaridade: Mestrado, Escolaridade: Doutorado, Gasto Total, Gasto com Produtos Regulares, Total de Campanhas Aceitas, Estado Civil, Nível de Escolaridade, Total de Filhos, Despesas]
Index: []

[0 rows x 44 columns]

> As incosistências encontradas não eram, na verdade, uma diferença de valores. `Gasto com Produtos Regulares` é uma coluna derivada: `Gasto Total` - `Gasto com Produtos Premium`. Logo, se o Premium for maior que o Total, o resultado fica negativo — é um erro de cálculo, não um dado ausente.

### 2.4 Outliers Brutos
Valores absurdos que indicam erro de coleta, distintos de outliers estatísticos legítimos.

In [69]:
df.describe()

,Unnamed: 0,Renda,Crianças em Casa,Adolescentes em Casa,Recência,Gasto com Vinhos,Gasto com Frutas,Gasto com Carnes,Gasto com Peixes,Gasto com Doces,...,Escolaridade: 2º Ciclo,Escolaridade: Ensino Básico,Escolaridade: Graduação,Escolaridade: Mestrado,Escolaridade: Doutorado,Gasto Total,Gasto com Produtos Regulares,Total de Campanhas Aceitas,Total de Filhos,Despesas
count,"2,205.00","2,205.00","2,205.00","2,205.00","2,205.00","2,205.00","2,205.00","2,205.00","2,205.00","2,205.00",...,198.00,54.00,"1,113.00",364.00,476.00,"2,205.00","2,205.00","2,205.00","2,205.00","2,205.00"
mean,"1,102.00","51,622.09",0.44,0.51,49.01,306.16,26.40,165.31,37.76,27.13,...,1.00,2.00,3.00,4.00,5.00,562.76,518.98,0.30,0.95,562.76
std,636.67,"20,713.06",0.54,0.54,28.93,337.49,39.78,217.78,54.82,41.13,...,0.00,0.00,0.00,0.00,0.00,575.94,553.54,0.68,0.75,575.94
min,0.00,"1,730.00",0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,...,1.00,2.00,3.00,4.00,5.00,4.00,0.00,0.00,0.00,4.00
25%,551.00,"35,196.00",0.00,0.00,24.00,24.00,2.00,16.00,3.00,1.00,...,1.00,2.00,3.00,4.00,5.00,56.00,42.00,0.00,0.00,56.00
50%,"1,102.00","51,287.00",0.00,0.00,49.00,178.00,8.00,68.00,12.00,8.00,...,1.00,2.00,3.00,4.00,5.00,343.00,288.00,0.00,1.00,343.00
75%,"1,653.00","68,281.00",1.00,1.00,74.00,507.00,33.00,232.00,50.00,34.00,...,1.00,2.00,3.00,4.00,5.00,964.00,884.00,0.00,1.00,964.00
max,"2,204.00","113,734.00",2.00,2.00,99.00,"1,493.00",199.00,"1,725.00",259.00,262.00,...,1.00,2.00,3.00,4.00,5.00,"2,491.00","2,458.00",4.00,3.00,"2,491.00"

### 2.5 Cardinalidade de Categóricas
Colunas com milhares de categorias únicas podem ser IDs disfarçados, não variáveis analíticas.

---
## **3. Medidas de Tendência Central**

Respondem: onde os dados estão concentrados?

| Medida | Definição | Quando usar |
|--------|-----------|-------------|
| **Média** | Soma dividida pela quantidade | Distribuições simétricas, sem outliers extremos |
| **Mediana** | Valor central quando ordenado | Distribuições assimétricas (renda, preço de imóvel) |
| **Moda** | Valor mais frequente | Variáveis categóricas ou discretas |
| **Média aparada (trimmed mean)** | Média excluindo os X% extremos | Quando há outliers mas não quer usar só a mediana |

Serve para: ter um "valor típico" de referência para cada variável numérica.

### 3.1 Média
Soma dividida pela quantidade. Sensível a outliers; indicada para distribuições simétricas.

$$\bar{x} = \frac{1}{n}\sum_{i=1}^{n} x_i$$

### 3.2 Mediana
Valor central quando os dados estão ordenados. Robusta a outliers; preferível em distribuições assimétricas.

$$\tilde{x} = \begin{cases} x_{\frac{n+1}{2}} & \text{se } n \text{ é ímpar} \\ \dfrac{x_{\frac{n}{2}} + x_{\frac{n}{2}+1}}{2} & \text{se } n \text{ é par} \end{cases}$$

### 3.3 Moda
Valor mais frequente. Única medida de tendência central aplicável a variáveis categóricas.

$$Mo = \underset{x}{\operatorname{argmax}}\; f(x)$$

### 3.4 Média Aparada (Trimmed Mean)
Média calculada excluindo os $\alpha$% extremos de cada lado — equilíbrio entre a média e a mediana quando há outliers.

$$\bar{x}_{\alpha} = \frac{1}{n - 2\lfloor\alpha n\rfloor} \sum_{i=\lfloor\alpha n\rfloor+1}^{n-\lfloor\alpha n\rfloor} x_{(i)}$$

---
## **4. Medidas de Dispersão**

Respondem: os dados estão espalhados ou concentrados?

| Medida | Definição | Quando usar |
|--------|-----------|-------------|
| **Variância** | Média dos quadrados dos desvios | Base teórica, mas difícil de interpretar |
| **Desvio padrão** | Raiz da variância, mesma unidade dos dados | Principal medida de dispersão |
| **Amplitude** | Máximo − Mínimo | Rápido, mas sensível a outliers |
| **IQR (Intervalo Interquartil)** | Q3 − Q1 (50% centrais) | Robusto a outliers, base do boxplot |
| **CV (Coeficiente de Variação)** | Desvio padrão / Média | Comparar dispersão entre variáveis em escalas diferentes |

Serve para: entender se a média é representativa ou se os dados são muito heterogêneos.

### 4.1 Variância
Média dos quadrados dos desvios em relação à média. Base teórica de outras métricas de dispersão.

$$s^2 = \frac{1}{n-1}\sum_{i=1}^{n}(x_i - \bar{x})^2$$

### 4.2 Desvio Padrão
Raiz quadrada da variância, expressa na mesma unidade dos dados. Medida de dispersão mais interpretável.

$$s = \sqrt{\frac{1}{n-1}\sum_{i=1}^{n}(x_i - \bar{x})^2}$$

### 4.3 Amplitude
Máximo − Mínimo. Simples e rápida de calcular, porém muito sensível a outliers.

$$A = x_{\max} - x_{\min}$$

### 4.4 IQR (Intervalo Interquartil)
Q3 − Q1, representando os 50% centrais dos dados. Robusto a outliers e base do boxplot.

$$IQR = Q_3 - Q_1$$

### 4.5 CV (Coeficiente de Variação)
Desvio padrão dividido pela média. Permite comparar dispersão entre variáveis com escalas diferentes.

$$CV = \frac{s}{\bar{x}} \times 100\%$$

---
## **5. Distribuição e Forma**

Respondem: qual o formato da distribuição dos dados?

- **Histograma** — visualiza a forma da distribuição
- **Boxplot** — mostra mediana, IQR e outliers de forma compacta
- **KDE (Kernel Density Estimation)** — versão suavizada do histograma
- **Assimetria (Skewness)** — distribuição puxada para a direita (positiva) ou esquerda (negativa)
- **Curtose (Kurtosis)** — cauda mais pesada ou mais leve que a normal (detecta risco de outliers extremos)
- **Teste de normalidade** — Shapiro-Wilk, Kolmogorov-Smirnov (muitos modelos assumem normalidade)

Serve para: escolher as transformações corretas (log, sqrt), identificar o tipo certo de teste estatístico e entender riscos de outliers.

### 5.1 Histograma
Divide os valores em intervalos e conta a frequência de cada faixa.

### 5.2 Boxplot
Representa visualmente mediana, IQR, mínimo, máximo e outliers de forma compacta.

### 5.3 KDE (Kernel Density Estimation)
Estimativa suavizada da densidade de probabilidade — versão contínua do histograma, útil para comparar distribuições sobrepostas.

### 5.4 Assimetria (Skewness)
Mede o grau e a direção da assimetria da distribuição em torno da média.

### 5.5 Curtose (Kurtosis)
Mede o peso das caudas — distribuições leptocúrticas têm caudas pesadas e maior risco de outliers extremos.

### 5.6 Teste de Normalidade
Shapiro-Wilk e Kolmogorov-Smirnov verificam formalmente se a distribuição é normal.

---
## **6. Análise de Outliers**

- **Método IQR** — valores abaixo de Q1 − 1.5×IQR ou acima de Q3 + 1.5×IQR
- **Z-score** — valores com |z| > 3 (mais de 3 desvios padrões da média)
- **Isolation Forest / LOF** — métodos de ML para outliers multivariados
- **Visualização** — boxplot, scatter plot com cores, violin plot

Serve para: decidir se o outlier é erro, evento raro legítimo ou informação valiosa. A decisão impacta direto na modelagem.

### 6.1 Método IQR
Considera outlier qualquer valor abaixo de Q1 − 1.5×IQR ou acima de Q3 + 1.5×IQR.

### 6.2 Z-Score
Considera outlier qualquer valor com |z| > 3, ou seja, além de 3 desvios padrões da média.

### 6.3 Isolation Forest / LOF
Algoritmos de ML que detectam outliers multivariados sem depender de uma única dimensão.

### 6.4 Visualização
Boxplot, scatter plot com destaque por cor e violin plot para identificar outliers visualmente.

---
## **7. Análise Univariada de Categóricas**

- **Frequência absoluta e relativa** — contagem e percentual de cada categoria
- **Gráfico de barras** — visualização da distribuição
- **Detecção de categorias raras** — categorias com < 1% de representatividade podem ser agrupadas
- **Análise de cardinalidade** — variáveis com alta cardinalidade exigem encoding cuidadoso

Serve para: entender o desbalanceamento entre categorias, que afeta modelos de classificação e análises comparativas.

### 7.1 Frequência Absoluta e Relativa
Contagem e percentual de cada categoria na variável.

### 7.2 Gráfico de Barras
Visualização da distribuição entre categorias, ordenável por frequência para facilitar a leitura.

### 7.3 Detecção de Categorias Raras
Categorias com representatividade abaixo de 1% podem ser agrupadas em "outros" para reduzir ruído.

### 7.4 Análise de Cardinalidade
Número de categorias únicas — alta cardinalidade exige encoding cuidadoso antes da modelagem.

---
## **8. Análise Bivariada**

Responde: como duas variáveis se relacionam entre si?

**Numérica × Numérica**
- **Scatter plot** — visualiza a relação e padrões
- **Correlação de Pearson** — relação linear (sensível a outliers)
- **Correlação de Spearman** — relação monotônica, robusta a outliers
- **Correlação de Kendall** — melhor para amostras pequenas

**Numérica × Categórica**
- **Boxplot agrupado** — compara distribuições por grupo
- **Violin plot** — mostra a densidade por grupo
- **Teste t / ANOVA** — verifica se as médias diferem estatisticamente entre grupos

**Categórica × Categórica**
- **Tabela de contingência (crosstab)** — frequência cruzada
- **Heatmap de frequência** — visualização da tabela
- **Teste qui-quadrado (χ²)** — verifica independência entre categóricas

Serve para: encontrar relações que guiarão a engenharia de features e a escolha do modelo.

### 8.1 Numérica × Numérica
Scatter plot, correlação de Pearson (linear), Spearman (monotônica) e Kendall (amostras pequenas).

### 8.2 Numérica × Categórica
Boxplot agrupado, violin plot e testes t / ANOVA para verificar se as médias diferem entre grupos.

### 8.3 Categórica × Categórica
Tabela de contingência (crosstab), heatmap de frequência e teste qui-quadrado (χ²) para verificar independência.

---
## **9. Análise Multivariada**

Responde: como várias variáveis interagem ao mesmo tempo?

- **Heatmap de correlação** — matriz de correlações de todas as numéricas de uma vez
- **Pair plot (Scatter Matrix)** — scatter de todos os pares de variáveis, com distribuição na diagonal
- **PCA (Análise de Componentes Principais)** — reduz dimensionalidade mantendo a máxima variância; útil para visualizar clusters em 2D
- **t-SNE / UMAP** — redução não-linear para visualização de grupos complexos
- **Cluster analysis exploratório (K-Means, DBSCAN)** — identifica grupos naturais antes de qualquer modelagem supervisionada
- **Análise de multicolinearidade (VIF)** — detecta variáveis redundantes que prejudicam regressões

Serve para: entender a estrutura global dos dados, detectar redundâncias e grupos ocultos.

### 9.1 Heatmap de Correlação
Matriz visual com o coeficiente de correlação entre todas as variáveis numéricas de uma vez.

### 9.2 Pair Plot (Scatter Matrix)
Grade de scatter plots para todos os pares de variáveis, com a distribuição individual na diagonal.

### 9.3 PCA (Análise de Componentes Principais)
Reduz dimensionalidade preservando a máxima variância — útil para visualizar clusters em 2D.

### 9.4 t-SNE / UMAP
Técnicas de redução não-linear para visualizar agrupamentos em datasets de alta dimensionalidade.

### 9.5 Cluster Analysis Exploratório (K-Means, DBSCAN)
Identifica agrupamentos naturais nos dados antes de qualquer modelagem supervisionada.

### 9.6 Análise de Multicolinearidade (VIF)
Variance Inflation Factor detecta variáveis redundantes que prejudicam modelos de regressão.

---
## **10. Análise Temporal (se houver datas)**

- **Série temporal** — evolução de métricas ao longo do tempo
- **Sazonalidade** — padrões que se repetem (diário, semanal, anual)
- **Tendência** — crescimento ou queda estrutural
- **Decomposição de série** — separa tendência + sazonalidade + resíduo
- **Lag features** — correlação de uma variável com ela mesma em períodos anteriores (autocorrelação)

Serve para: evitar data leakage em modelos temporais e entender padrões de comportamento ao longo do tempo.

### 10.1 Série Temporal
Visualização da evolução de uma métrica ao longo do tempo.

### 10.2 Sazonalidade
Padrões cíclicos que se repetem em intervalos regulares — diário, semanal ou anual.

### 10.3 Tendência
Direção geral de crescimento ou queda estrutural ao longo do período analisado.

### 10.4 Decomposição de Série
Separa a série em três componentes: tendência, sazonalidade e resíduo.

### 10.5 Lag Features
Correlação de uma variável com versões defasadas de si mesma — base para detecção de autocorrelação.

---
## **11. Análise de Texto (se houver variáveis textuais)**

- **Comprimento dos textos** — distribuição de tamanho
- **Nuvem de palavras** — frequência visual
- **N-gramas mais frequentes** — bigramas, trigramas relevantes
- **Sentimento médio** — se o contexto de negócio justificar

Serve para: identificar padrões linguísticos, ruídos e oportunidades de feature engineering em variáveis textuais.

### 11.1 Comprimento dos Textos
Distribuição do número de caracteres ou palavras — textos muito curtos ou longos podem indicar problemas de qualidade.

### 11.2 Nuvem de Palavras
Representação visual da frequência dos termos mais recorrentes no corpus.

### 11.3 N-gramas Mais Frequentes
Bigramas e trigramas revelam padrões de linguagem mais ricos do que palavras isoladas.

### 11.4 Sentimento Médio
Análise de polaridade (positivo / negativo / neutro) quando o contexto de negócio justificar.

---
## **12. Resumo e Hipóteses**

A etapa final da EDA não é técnica, é interpretativa.

- **Listar achados principais** — o que chamou atenção?
- **Levantar hipóteses** — "parece que X influencia Y por causa de Z"
- **Definir o que precisa ser tratado** — missings, outliers, transformações, encodings
- **Documentar decisões** — por que você escolheu tratar (ou não) cada problema encontrado

Serve para: transformar números e gráficos em entendimento de negócio. É o que diferencia uma EDA rasa de uma análise que realmente orienta decisões.

### 12.1 Listar Achados Principais
Registrar o que chamou atenção — variáveis com comportamento inesperado, correlações fortes, desequilíbrios.

### 12.2 Levantar Hipóteses
Formalizar intuições geradas pela análise — "parece que X influencia Y por causa de Z".

### 12.3 Definir o que Precisa ser Tratado
Consolidar o backlog de pré-processamento — missings, outliers, transformações, encodings.

### 12.4 Documentar Decisões
Registrar por que cada problema foi ou não tratado, criando rastreabilidade para o modelo.